-- 코드를 입력하세요
SELECT CAR_ID, ROUND(SUM(DATEDIFF(END_DATE, START_DATE)+1)/COUNT(CAR_ID),1) as AVERAGE_DURATION from CAR_RENTAL_COMPANY_RENTAL_HISTORY group by car_id having AVERAGE_DURATION>=7 order by AVERAGE_DURATION DESC, CAR_ID DESC

# SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE) from CAR_RENTAL_COMPANY_RENTAL_HISTORY order by  CAR_ID DESC
